### ISSUE TITLE
InProcess and Output from ASP.NET Core Web Server in Visual Studio

### ISSUE THREAD

**Issue by zerox981** [aspnet/Docs#10307]
When using `<AspNetCoreHostingModel>InProcess</AspNetCoreHostingModel>` you lose Show output from: ASP.NET Core Web Server in Visual Studio

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fe69b3a9-896f-e189-0c2c-f87ff735df9c
* Version Independent ID: 97c8549b-66ad-0a23-1971-784fb923042a
* Content: [ASP.NET Core Module](https://docs.microsoft.com/en-us/aspnet/core/host-and-deploy/aspnet-core-module?view=aspnetcore-2.2#hosting-models)
* Content Source: [aspnetcore/host-and-deploy/aspnet-core-module.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/host-and-deploy/aspnet-core-module.md)
* Product: **aspnet-core**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Hello @zerox981 ... Yes, that's correct here, too.

@Tratcher How should we doc this, if at all.

**Comment by Tratcher** [comment]
@shirhatti @BillHiebert @pakrym @jkotalik

**Comment by Rick-Anderson** [comment]
When using `<AspNetCoreHostingModel>InProcess</AspNetCoreHostingModel>` you lose Show output from: ASP.NET Core Web Server in Visual Studio

@shirhatti @BillHiebert @pakrym @jkotalik

**Comment by shirhatti** [comment]
Known issue. Has been fixed in Visual Studio 16.0-preview4.

**Comment by guardrex** [comment]
Since this is fixed in an upcoming release and we don't version topic content by VS release, let's not address this.

**Comment by gilmishal** [comment]
I am using Visual Studio 2019 16.0 and the issue is back. It used to work when I was on the preview branch.

**Comment by guardrex** [comment]
@gilmishal Push that feedback to the VS team using the "Report a problem" process built into VS. Those reports go directly to that team for triage.
