### ISSUE TITLE
Where is the fix for the "No type was specified for the decimal column" migration error?

### ISSUE THREAD

**Issue by danielcongrove** [aspnet/Docs#8414]
> Ignore the following warning message, you fix that in the next tutorial:
> 
> Microsoft.EntityFrameworkCore.Model.Validation[30000]
> 
> No type was specified for the decimal column 'Price' on entity type 'Movie'. This will cause values to be silently truncated if they do not fit in the default precision and scale. Explicitly specify the SQL server column type that can accommodate all the values using 'ForHasColumnType()'.

Source: https://docs.microsoft.com/en-us/aspnet/core/tutorials/razor-pages/model?view=aspnetcore-2.1

The article mentions that the fix is in the next tutorial, but I cannot find it anywhere. Can anyone point to the location of the solution?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6719f08e-3bd7-dc1a-71df-f2ef9fbca9d8
* Version Independent ID: 7096fdb3-612e-9e00-bd0b-8ea4886a09ce
* Content: [Add a model to a Razor Pages app in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/tutorials/razor-pages/model?view=aspnetcore-2.1)
* Content Source: [aspnetcore/tutorials/razor-pages/model.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/tutorials/razor-pages/model.md)
* Product: **aspnet-core**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
@danielcongrove I should read "in a later tutorial". It's just a warning. I fixed the wording.

**Comment by leniency** [comment]
But where's the later tutorial? This doesn't fix the basic question.

**Comment by Rick-Anderson** [comment]
https://docs.microsoft.com/en-us/aspnet/core/tutorials/razor-pages/new-field

```
public class Movie
{
    public int ID { get; set; }
    public string Title { get; set; }

    [Display(Name = "Release Date")]
    [DataType(DataType.Date)]
    public DateTime ReleaseDate { get; set; }
    public string Genre { get; set; }

    [Column(TypeName = "decimal(18, 2)")]
    public decimal Price { get; set; }
    public string Rating { get; set; }
}
```

**Comment by AlbertLi255** [comment]
Looks like no fix to now.

**Comment by StudentShaga** [comment]
11 апреля 2025 невозможно ничего сделать. Десятичные числа не вводятся. Ошибка!
